name: update-readme

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GENERATE_README
        run: bash ./gen.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GITHUB_GENERATOR
          author_email: zhengzongwei@foxmail.com
          message: "AUTO GENERATE README"
          add: "*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
